//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace leave_salary.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class leaveapp
    {
        public int id { get; set; }
        public Nullable<int> empid { get; set; }
        public string typeofleave { get; set; }
        public Nullable<System.DateTime> startdate { get; set; }
        public Nullable<System.DateTime> enddate { get; set; }
        public string comments { get; set; }
        public string ApplyforLeave { get; set; }
    
        public virtual basic1 basic1 { get; set; }
    }
}
